config/routes.rb
Rails.application.routes.draw do
  root to:'toppages#index'

  resources:categories do
    resources:blogs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @blogs = @category.blogs
  end

  def new
    @category = Category.find(params[:category_id])
    @blog = @category.blogs.build
  end

  def create
    @category = Category.find(params[:category_id])
    @blog = @category.blogs.build(blog_params)
    if @blog.save(blog_params)
      redirect_to category_blogs_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @blog = @category.blogs.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @blog = @category.blogs.find(params[:id])
    if @blog.update(blog_params)
      redirect_to category_blogs_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @blog = @category.blogs.find(params[:id])
    @blog.destroy
    redirect_to category_blogs_path
  end


  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
    
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:cate_name)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/blogs/edit.html.haml
= form_with model: [@category, @blog], local: true do |f|
  = f.label :title, "タイトル"
  = f.text_field :title
  = f.label :content, "内容"
  = f.text_field :content
  = f.submit "作成"

app/views/blogs/index.html.haml
%div= link_to "作成",  new_category_blog_path
%table
  %thead
    %tr
      %th タイトル
      %th 内容
  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td= blog.content
        %td= link_to '編集', edit_category_blog_path(@category, blog), class: 'btn btn-success'
        %td= link_to '削除', category_blog_path(@category, blog), method: :delete, data: {confirm: "削除します"}, class: 'btn btn-danger delete'

app/views/blogs/new.html.haml
= form_with model: [@category, @blog], local: true do |f|
  = f.label :title, "タイトル"
  = f.text_field :title
  = f.label :content, "内容"
  = f.text_field :content
  = f.submit "作成"

app/views/categories/edit.html.haml
= form_with model: @category, local: true do |f|
  = f.label :cate_name, "カテゴリー"
  = f.text_field :cate_name
  = f.submit "作成"

app/views/categories/index.html.haml
%div= link_to "作成",  new_category_path
%table
  %thead
    %tr
      %th カテゴリー
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to "#{category.cate_name}", category_blogs_path(category)
        %td= link_to '編集', edit_category_path(category), class: 'btn btn-success'
        %td= link_to '削除', category_path(category), method: :delete, data: {confirm: "削除します"}, class: 'btn btn-danger delete'

app/views/categories/new.html.haml
= form_with model: @category, local: true do |f|
  = f.label :cate_name, "カテゴリー"
  = f.text_field :cate_name
  = f.submit "作成"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DicDay08
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/toppages/index.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Creative - Start Bootstrap Theme
    / Bootstrap core CSS
    %link{:href => "vendor/bootstrap/css/bootstrap.min.css", :rel => "stylesheet"}/
    / Custom fonts for this template
    %link{:href => "vendor/fontawesome-free/css/all.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic", :rel => "stylesheet", :type => "text/css"}/
    / Plugin CSS
    %link{:href => "vendor/magnific-popup/magnific-popup.css", :rel => "stylesheet"}/
    / Custom styles for this template
    %link{:href => "css/creative.min.css", :rel => "stylesheet"}/
  %body#page-top
    / Navigation
    %nav#mainNav.navbar.navbar-expand-lg.navbar-light.fixed-top
      .container
        %a.navbar-brand.js-scroll-trigger{:href => "#page-top"} Start Bootstrap
        %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarResponsive.collapse.navbar-collapse
          %ul.navbar-nav.ml-auto
            %li.nav-item
              = link_to "作成", categories_path
            %li.nav-item
              %a.nav-link.js-scroll-trigger{:href => "#services"} Services
            %li.nav-item
              %a.nav-link.js-scroll-trigger{:href => "#portfolio"} Portfolio
            %li.nav-item
              %a.nav-link.js-scroll-trigger{:href => "#contact"} Contact
    %header.masthead.text-center.text-white.d-flex
      .container.my-auto
        .row
          .col-lg-10.mx-auto
            %h1.text-uppercase
              %strong Your Favorite Source of Free Bootstrap Themes
            %hr/
          .col-lg-8.mx-auto
            %p.text-faded.mb-5 Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!
            %a.btn.btn-primary.btn-xl.js-scroll-trigger{:href => "#about"} Find Out More
    %section#about.bg-primary
      .container
        .row
          .col-lg-8.mx-auto.text-center
            %h2.section-heading.text-white We've got what you need!
            %hr.light.my-4/
            %p.text-faded.mb-4 Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!
            %a.btn.btn-light.btn-xl.js-scroll-trigger{:href => "#services"} Get Started!
    %section#services
      .container
        .row
          .col-lg-12.text-center
            %h2.section-heading At Your Service
            %hr.my-4/
      .container
        .row
          .col-lg-3.col-md-6.text-center
            .service-box.mt-5.mx-auto
              %i.fas.fa-4x.fa-gem.text-primary.mb-3.sr-icon-1
              %h3.mb-3 Sturdy Templates
              %p.text-muted.mb-0 Our templates are updated regularly so they don't break.
          .col-lg-3.col-md-6.text-center
            .service-box.mt-5.mx-auto
              %i.fas.fa-4x.fa-paper-plane.text-primary.mb-3.sr-icon-2
              %h3.mb-3 Ready to Ship
              %p.text-muted.mb-0 You can use this theme as is, or you can make changes!
          .col-lg-3.col-md-6.text-center
            .service-box.mt-5.mx-auto
              %i.fas.fa-4x.fa-code.text-primary.mb-3.sr-icon-3
              %h3.mb-3 Up to Date
              %p.text-muted.mb-0 We update dependencies to keep things fresh.
          .col-lg-3.col-md-6.text-center
            .service-box.mt-5.mx-auto
              %i.fas.fa-4x.fa-heart.text-primary.mb-3.sr-icon-4
              %h3.mb-3 Made with Love
              %p.text-muted.mb-0 You have to make your websites with love these days!
    %section#portfolio.p-0
      .container-fluid.p-0
        .row.no-gutters.popup-gallery
          .col-lg-4.col-sm-6
            %a.portfolio-box{:href => "img/portfolio/fullsize/1.jpg"}
              %img.img-fluid{:alt => "", :src => "img/portfolio/thumbnails/1.jpg"}/
              .portfolio-box-caption
                .portfolio-box-caption-content
                  .project-category.text-faded
                    Category
                  .project-name
                    Project Name
          .col-lg-4.col-sm-6
            %a.portfolio-box{:href => "img/portfolio/fullsize/2.jpg"}
              %img.img-fluid{:alt => "", :src => "img/portfolio/thumbnails/2.jpg"}/
              .portfolio-box-caption
                .portfolio-box-caption-content
                  .project-category.text-faded
                    Category
                  .project-name
                    Project Name
          .col-lg-4.col-sm-6
            %a.portfolio-box{:href => "img/portfolio/fullsize/3.jpg"}
              %img.img-fluid{:alt => "", :src => "img/portfolio/thumbnails/3.jpg"}/
              .portfolio-box-caption
                .portfolio-box-caption-content
                  .project-category.text-faded
                    Category
                  .project-name
                    Project Name
          .col-lg-4.col-sm-6
            %a.portfolio-box{:href => "img/portfolio/fullsize/4.jpg"}
              %img.img-fluid{:alt => "", :src => "img/portfolio/thumbnails/4.jpg"}/
              .portfolio-box-caption
                .portfolio-box-caption-content
                  .project-category.text-faded
                    Category
                  .project-name
                    Project Name
          .col-lg-4.col-sm-6
            %a.portfolio-box{:href => "img/portfolio/fullsize/5.jpg"}
              %img.img-fluid{:alt => "", :src => "img/portfolio/thumbnails/5.jpg"}/
              .portfolio-box-caption
                .portfolio-box-caption-content
                  .project-category.text-faded
                    Category
                  .project-name
                    Project Name
          .col-lg-4.col-sm-6
            %a.portfolio-box{:href => "img/portfolio/fullsize/6.jpg"}
              %img.img-fluid{:alt => "", :src => "img/portfolio/thumbnails/6.jpg"}/
              .portfolio-box-caption
                .portfolio-box-caption-content
                  .project-category.text-faded
                    Category
                  .project-name
                    Project Name
    %section.bg-dark.text-white
      .container.text-center
        %h2.mb-4 Free Download at Start Bootstrap!
        %a.btn.btn-light.btn-xl.sr-button{:href => "http://startbootstrap.com/template-overviews/creative/"} Download Now!
    %section#contact
      .container
        .row
          .col-lg-8.mx-auto.text-center
            %h2.section-heading Let's Get In Touch!
            %hr.my-4/
            %p.mb-5 Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!
        .row
          .col-lg-4.ml-auto.text-center
            %i.fas.fa-phone.fa-3x.mb-3.sr-contact-1
            %p 123-456-6789
          .col-lg-4.mr-auto.text-center
            %i.fas.fa-envelope.fa-3x.mb-3.sr-contact-2
            %p
              %a{:href => "mailto:your-email@your-domain.com"} feedback@startbootstrap.com
    / Bootstrap core JavaScript
    %script{:src => "vendor/jquery/jquery.min.js"}
    %script{:src => "vendor/bootstrap/js/bootstrap.bundle.min.js"}
    / Plugin JavaScript
    %script{:src => "vendor/jquery-easing/jquery.easing.min.js"}
    %script{:src => "vendor/scrollreveal/scrollreveal.min.js"}
    %script{:src => "vendor/magnific-popup/jquery.magnific-popup.min.js"}
    / Custom scripts for this template
    %script{:src => "js/creative.min.js"}